spring:
  application:
    name: netflix-eureka-client-service-consumer
  aop:
    proxy-target-class: true
eureka:
  instance:
    appname: netflix-eureka-client-service-consumer
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
          defaultZone: http://127.0.0.1:8761/eureka/
server:
  port: 8001

