spring:
  application:
    name: netflix-eureka-client-service-gateway
  aop:
    proxy-target-class: true
eureka:
  instance:
    appname: netflix-eureka-client-service-gateway
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
          defaultZone: http://127.0.0.1:8761/eureka/
server:
  port: 3000

feign:
  hystrix:
    enabled: true