spring:
  application:
    name: netflix-eureka-server-second
eureka:
  instance:
    appname: netflix-eureka-server-second
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
server:
  port: 8762




