server:
  port: 8761

eureka:
  instance:
    appname: netflix-eureka-server
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8762/eureka/
spring:
  application:
    name: netflix-eureka-server




