spring:
  application:
    name: netflix-zuul-gateway
eureka:
  instance:
    appname: netflix-zuul-gateway
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
          defaultZone: http://127.0.0.1:8761/eureka/

server:
  port: 5000

zuul:
  routes:
    api:
      path: /api/**
      serviceId: netflix-eureka-client-service-consumer